# based on https://github.com/snapcore/snapcraft/blob/master/demos/gradle/snap/snapcraft.yaml

name: jabref
version: '4.0-dev'
summary: Bibliography manager
icon: src/main/resources/images/external/JabRef-icon-128.png
description: JabRef is an open source bibliography reference manager. The native file format used by JabRef is BibTeX, the standard LaTeX bibliography format.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
   jabref:
     command: java -jar $SNAP/jar/JabRef-4.0-dev.jar

parts:
  jabref:
    plugin: gradle
    source: .
    stage-packages: [default-jre, openjfx]
    gradle-options: [snapJar]
    gradle-output-dir: 'build/releases'
